package provisEntities

type FamilyPerson struct {
	IDPersona                                   int           `json:"idPersona"`
	IDInstalacion                               int           `json:"idInstalacion"`
	IDTipoDeCliente                             int           `json:"idTipoDeCliente"`
	NombreTipoDeCliente                         interface{}   `json:"nombreTipoDeCliente"`
	Codigo                                      int           `json:"codigo"`
	TipoDocumento                               interface{}   `json:"tipoDocumento"`
	NIF                                         string        `json:"nif"`
	TarjetaAcceso                               interface{}   `json:"tarjetaAcceso"`
	Email                                       string        `json:"email"`
	Nombre                                      string        `json:"nombre"`
	Apellidos                                   string        `json:"apellidos"`
	FechaDeNacimiento                           string        `json:"fechaDeNacimiento"`
	Telefono1                                   string        `json:"telefono1"`
	Telefono2                                   string        `json:"telefono2"`
	IDPaisMovil                                 int           `json:"idPaisMovil"`
	Movil                                       string        `json:"movil"`
	Direccion                                   string        `json:"direccion"`
	Localidad                                   string        `json:"localidad"`
	CP                                          string        `json:"cp"`
	IDProvincia                                 int           `json:"idProvincia"`
	CodigoPais                                  interface{}   `json:"codigoPais"`
	IDPais                                      int           `json:"idPais"`
	CodBanco                                    string        `json:"codBanco"`
	CodSucursal                                 string        `json:"codSucursal"`
	DC                                          string        `json:"dc"`
	NumeroDeCuenta                              string        `json:"numeroDeCuenta"`
	IBAN                                        string        `json:"iban"`
	BIC                                         string        `json:"bic"`
	NumeroDeCuentaUE                            interface{}   `json:"numeroDeCuentaUE"`
	Nick                                        string        `json:"nick"`
	Sexo                                        string        `json:"sexo"`
	EsCabezaDeFamilia                           interface{}   `json:"esCabezaDeFamilia"`
	EnviarMailings                              int           `json:"enviarMailings"`
	EnviarSMS                                   int           `json:"enviarSMS"`
	EnviarEmails                                int           `json:"enviarEmails"`
	Contrasenia                                 interface{}   `json:"contrasenia"`
	PIN                                         interface{}   `json:"pin"`
	UltimaFechaDeAlta                           string        `json:"ultimaFechaDeAlta"`
	UltimaFechaDeBaja                           string        `json:"ultimaFechaDeBaja"`
	PagosPersonas                               interface{}   `json:"pagosPersonas"`
	EstadosPersonas                             interface{}   `json:"estadosPersonas"`
	CuotasPersonas                              interface{}   `json:"cuotasPersonas"`
	CuotasPersonasAnteriores                    interface{}   `json:"cuotasPersonasAnteriores"`
	Bonos                                       interface{}   `json:"bonos"`
	MatriculasPersonas                          interface{}   `json:"matriculasPersonas"`
	AccesosPersonas                             interface{}   `json:"accesosPersonas"`
	ClasesColectivasPersonas                    interface{}   `json:"clasesColectivasPersonas"`
	PersonasDirecciones                         interface{}   `json:"personasDirecciones"`
	FechaNotificacionLOPD                       interface{}   `json:"fechaNotificacionLOPD"`
	PermitirNotificacionesComercialesLOPD       bool          `json:"permitirNotificacionesComercialesLOPD"`
	TipoDeAceptacionLOPD                        interface{}   `json:"tipoDeAceptacionLOPD"`
	FechaNotificacionLOPDEnBaja                 interface{}   `json:"fechaNotificacionLOPDEnBaja"`
	PermitirNotificacionesComercialesLOPDEnBaja interface{}   `json:"permitirNotificacionesComercialesLOPDEnBaja"`
	TipoDeAceptacionLOPDEnBaja                  interface{}   `json:"tipoDeAceptacionLOPDEnBaja"`
	EnviarNotificaciones                        bool          `json:"enviarNotificaciones"`
	EnviarMailingsComerciales                   bool          `json:"enviarMailingsComerciales"`
	EnviarSMSComerciales                        bool          `json:"enviarSMSComerciales"`
	EnviarEmailsComerciales                     bool          `json:"enviarEmailsComerciales"`
	EnviarNotificacionesComerciales             bool          `json:"enviarNotificacionesComerciales"`
	PermitirCompartirEnRedesSociales            interface{}   `json:"permitirCompartirEnRedesSociales"`
	PermitirCompartirDatosATerceros             interface{}   `json:"permitirCompartirDatosATerceros"`
	ListaIdentificadoresDeAcceso                []interface{} `json:"listaIdentificadoresDeAcceso"`
	ImagenPersona                               interface{}   `json:"imagenPersona"`
	Profesion                                   interface{}   `json:"profesion"`
	IDPaisCuentaCorriente                       int           `json:"idPaisCuentaCorriente"`
	ListaTutores                                []interface{} `json:"listaTutores"`
	PermitirUtilizarDatosBiometricos            interface{}   `json:"permitirUtilizarDatosBiometricos"`
	ListaVarios                                 interface{}   `json:"listaVarios"`
	ListaMotivosBaja                            interface{}   `json:"listaMotivosBaja"`
	CampoLibre1                                 interface{}   `json:"campoLibre1"`
	CampoLibre2                                 interface{}   `json:"campoLibre2"`
	CampoLibre3                                 interface{}   `json:"campoLibre3"`
	CampoLibre4                                 interface{}   `json:"campoLibre4"`
	CampoLibre5                                 interface{}   `json:"campoLibre5"`
	FechaLibre1                                 interface{}   `json:"fechaLibre1"`
	FechaLibre2                                 interface{}   `json:"fechaLibre2"`
	FechaLibre3                                 interface{}   `json:"fechaLibre3"`
	FechaLibre4                                 interface{}   `json:"fechaLibre4"`
	FechaLibre5                                 interface{}   `json:"fechaLibre5"`
	CheckLibre1                                 interface{}   `json:"checkLibre1"`
	CheckLibre2                                 interface{}   `json:"checkLibre2"`
	CheckLibre3                                 interface{}   `json:"checkLibre3"`
	CheckLibre4                                 interface{}   `json:"checkLibre4"`
	CheckLibre5                                 interface{}   `json:"checkLibre5"`
}

// Para representar el array completo
type Familie struct {
	FamilyPersons []*FamilyPerson `json:"familyPersons"`
}
